### ISSUE TITLE
Will SPN be coming to MacOS?

### ISSUE THREAD

**Issue by CollinsVakayil** [safing/spn#103]
I would gladly ditch VPN for SPN, but unfortunately I'm unable to find anywhere on your site for subscriptions for MacOS. It just says it's unsupported. Is this something y'all plan support in the near future?

**Comment by CollinsVakayil** [comment]
Also do you have Enterprise/Corporate plans?

**Comment by dhaavi** [comment]
Hey @CollinsVakayil, thanks for the question.

Yes, we plan to support MacOS in the future. You read all about the details here: https://docs.safing.io/portmaster/install/status/mac

We are looking into enterprise plans too, with central management in one form or another. But this is further out.
