### ISSUE TITLE
Reaching kobo.com through spn only

### ISSUE THREAD

**Issue by boistordu** [safing/spn#112]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

Can't seem to reach  kobo.com through SPN.
Could you confirm me that?

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Seems to be down with or without the SPN.
Also reported here: https://isitup.org/www.kobo.com

**Comment by boistordu** [comment]
Strange because without SPN I can access it. Maybe then it has nothing to do about SPN and some bgp problems instead

**Comment by dhaavi** [comment]
Hm. Interesting. Maybe they are only allowing connections from certain areas or networks?

If you can find out which ones these are, I can save them and include them in a future update where we improve routing for destinations.
