### ISSUE TITLE
3 suggestions.

### ISSUE THREAD

**Issue by tuqueque** [safing/spn#12]
Hey, I just heard about this project and it looks really, really interesting!... but I have 3 "requirements" that if not implemented, are just "dealbreakers" for me… of course, if implemented, it would make this project the PERFECT tool for privacy.

1st requirement:
As far as I've read, you are implementing cryptocurrency payments, right?… But PLEASE, don't just accept Bitcoin, accept at least 3-5 options. My suggestions are: Bitcoin, Litecoin, Ethereum, Dash and at least one "stablecoin", like USDT or even better, DAI. Also, please, stay up to date to the protocols! Be compatible with SegWit (BIP84) addresses!

2nd requirement:
From what I've read, Safing SPN will "automatically" choose which nodes (servers) will connect to in order to offer the best connection speed/stability and so on… but a lot of times an user will NEED to specify an "exit node" (server) to avoid problems with a servise… I don't know if this is already implemented, but my suggestion is to allow the user to specify an exit node/server if they need to (of course, if the user doesn't need to or doesn't care, SPN will pick it automatically)... The SPN will still pick the intermediate nodes/servers, but let the user pick the exit node/server if they need to.

3rd requirement:
After trying Mullvad VPN's way of managing user accounts, I ABSOLUTELY WON'T USE anything that asks for an email to create an account, no matter the reason!… I understand you might want it to help the user recover a lost password or whatever, but I don't care. If you say you are better than a VPN regarding privacy, you're shooting yourselves on the foot with such a bad account system. Please, implement an anonymous system like Mullvad VPN, they're doing great with it and their users are pretty happy with it.

Once you solve those issues I mentioned above, you can count me as a faithful user, otherwise I'll just stick to a more private and practical VPN.

Greets!

**Comment by Raphty** [comment]
Hey tuqueque thanks for the great suggestions!

1. Yes we are working on btc eth and xmr. I like the suggestion of a stable coin! We will look into the options and probably add one soon maybe even together with the others. 
2. Our goal is to empower users as much as possible. So of course picking exit nodes will be possible in the future. Even on a connect by connection basis. So no more switching the whole system just to switch for one use case. But I can’t promise to what extent those capabilities will be available from the time you get acces to it. ATM in the closed alpha those settings aren’t available yet. but they will be the next features on the list. 
3. We don’t require a email from our users. we didn’t go with the mullvad model, we do require a password and we opted for a username model. For the username, you can pick your own or use the random generated one that is prefilled to avoide using the same usernames everywhere.

**Comment by tuqueque** [comment]
Hey, thank you for the quick and clear reply!

1.- That's great... although, please, pretty please with sugar on top, add Litecoin in the mix... BTC and ETH transfer fees are ridiculous most of the time!

2.- That's great also!... I understand this will/might not be in the initial release, but I hope is relatively high in the "to-do" list.

3.- Oh, this is totally my bad!... I should have paid more attention to the sign-up process and requirement. This is perfect!

Great job! Count on me as a future user!

P.S.: Also, please, never forget about Linux users! Remember to put the AUR package as soon as you're comfortable with releasing it!

**Comment by rz1027** [comment]
I like your Segwit solution but can I pay from a Binance Spot Wallet ? It doesn't show Segwit Binance only shows Lightning Network
