### ISSUE TITLE
Feature: SPN for PFsense

### ISSUE THREAD

**Issue by rwjack** [safing/spn#127]
**What would you like to add or change?**:
Spread your wings you beautiful peace of software!
By focusing on entire infrastructure sets instead of end-user devices only, a PFsense implementation would fare quite well!

**Why do you and others need this?**:
It's simple: So SPN can be installed on a router/firewall and have all devices/VMs/Selected subnets, go through the SPN.

**Comment by Raphty** [comment]
Thank you for the suggestion.

And we might do something like this in the far future.

At the moment we are focusing on making privacy more accessible to more people by making things easier.
