### ISSUE TITLE
Can't login and my account details show only the close button

### ISSUE THREAD

**Issue by herop** [safing/spn#140]
### What happened?
After PM started, SPN only always (even after restart) shows the blue &#34;UPGRADE&#34; button.
If I click it, the above mentioned happens even after trying for 3 consecutive days now.
I even deleted my computer profiles from my safing.io page.

### What did you expect to happen?
Well, that I can use SPN as expected and being able to login.

### How did you reproduce it?
As mentioned, for days now, with PM running the blue button shows up and no login is possible.

### Additional information

**Debug-Info**: https://support.safing.io/privatebin/?15e1735dddfb7956#HLZcv6pGrDKKwC82BLnbivSs3ys6jQqnrUsiDiSagpTy

**Comment by dhaavi** [comment]
Hey @herop, thanks for report!

I'm not sure how Portmaster could end up in that state, but you can try to enable the SPN in the global settings. This will update the account and might do the trick.

**Comment by herop** [comment]
![image](https://user-images.githubusercontent.com/658323/206745063-9671f10f-9ba2-4cea-a066-19adf65d97ac.png)
I tried that already — and failed.

**Comment by dhaavi** [comment]
Ok, this is weird.
You could try to log out manually via the API and then log in again.
See this issue on how to do that: https://github.com/safing/portmaster/issues/949#issuecomment-1286632408

What does the notification in the screenshot say?

Sorry for the inconvenience. We will look into it closer next week.
