### ISSUE TITLE
While SPN on, after PC is woken from sleep mode, Firefox [maybe others, haven't tested] more below

### ISSUE THREAD

**Issue by TrueBeastEmperor** [safing/spn#167]
While SPN on, after PC is woken from sleep mode, Firefox [maybe others, haven't tested] shows the following image: 
![image](https://user-images.githubusercontent.com/127135522/231837988-4ef910a9-539a-4f4d-a701-5aa19128c144.png)
And this happens almost every time PC comes out of sleep/hibernation mode. Don't know what it's called exactly. Also, the moment SPN is disabled, internet functionality is restored. In this case the browser used, Firefox, is not using SPN, or to be more specific, has SPN disabled.

Debug info: 
[Portmaster debug info 13.03.23 .txt](https://github.com/safing/intel-data/files/11224812/Portmaster.debug.info.13.03.23.txt)

**Comment by TrueBeastEmperor** [comment]
Hi @dhaavi 

No, sadly, it doesn't recover itself. Tried waiting for 5 minutes. It didn't fix itself. Yes, I have tried the v1.0.12. There were already recommendations for that in the Discord channel [Username: TrueDeath]. I need to manually close SPN module for it to work. Lately, though, I think I haven't noticed anything happening.

**Comment by Raphty** [comment]
Hey there @TrueBeastEmperor I am sorry that this issue has gone unresolved for so long. Portmaster has gotten some major updates in the meantime. Pleas open a new issue with new debug info so we can tackle the issue with the current situation

regards
