### ISSUE TITLE
Unattended install does still require input

### ISSUE THREAD

**Issue by NL-TCH** [safing/spn#173]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/spn/issues?q=is%3Aissue+label%3Abug)
  - [Broken Websites/Services](https://github.com/safing/spn/issues?q=is%3Aissue+label%3A%22website+compatibility%22)
  - [Network Status](https://github.com/safing/spn/issues?q=is%3Aissue+label%3A%22network%22%2C%22network+status%22)

**What happened**:
when installing the spn community node software with the following command `./install.sh -S -y -n` (with the -y for unattended)
we still get the following prompt:
`-> Please enter metrics comment:`

**What did you expect to happen?**:
I expected to not get the prompt because i chose for the unattended install

**How did you reproduce it?**:
via the install `./install.sh -S -y -n`

**Debug Information**:

**Comment by NL-TCH** [comment]
the workaround is: `yes | ./install.sh -S -y -n` and just enter 'yes' into the field

**Comment by Raphty** [comment]
@dhaavi I know this works for us, so what information would we need to understand what @NL-TCH issue might be?
