### ISSUE TITLE
Why hasn't the source code been updated for two months?

### ISSUE THREAD

**Issue by du82** [safing/spn#188]
Why hasnt the source code been updated for two months? Is SPN going closed source?

**Comment by dhaavi** [comment]
Hey @du82,

Is there a particular reason why you think the source code should have been updated in the last two months?

Also, is there a particular reason that makes you believe that SPN is going closed source?

**Comment by Raphty** [comment]
Portmaster and SPN are tightly interwoven. At this point it is the same people working on one and the other, Portmaster has gotten a lot of attention in the last couple of months (also in the SPN UI part, which is not in this Repository)
