### ISSUE TITLE
Crypto and stock exchanges

### ISSUE THREAD

**Issue by northys** [safing/spn#39]
**Which Website or Server are you having troubles with?**

Financial services like stock and crypto exchanges breaks when US node (any node outside Europe) is being used.

**What did not work?**

Most of exchanges breaks when exit node outside EU is being used.

**What could help?**

Option to select region of exit nodes for specific websites.

**Comment by dhaavi** [comment]
Where are the exchanges located?

We currently have one node that shows up in Europe, but is actually in the US (in the new Hetzner data center). That might be causing some trouble here.

Exit node selection is the next SPN thing on the roadmap - but gotta stabilize these servers first.

**Comment by dhaavi** [comment]
Update: Per-app exit selection is in progress.

Sadly, not yet per domain, see https://github.com/safing/portmaster/issues/508.
