### ISSUE TITLE
Home node

### ISSUE THREAD

**Issue by northys** [safing/spn#40]
**What would you like to add or change?**:

I would love if I could select which node is my home.

**Why do you and others need this?**:

Every node has a different ping to my home network and I know which one is fastest. Currently home nodes are picked randomly or by load. I always have to reconnect multiple times so I get connected to my favorite and fastest one.

I also expect that the servers have better / different / more expensive connection routes between each other than my ISP (and ISP above him) have so there is still higher chance that being connected from CZ to DE which goes through PL to FI could be much faster than reversed route from CZ to FI through PL to DE.

**Comment by dhaavi** [comment]
We are working on better routing, which will hopefully clear things up.
Home node selection will come with the exit node selection once the servers are stabilized.

**Comment by dhaavi** [comment]
Update: This is moving forward.
