### ISSUE TITLE
downloading at full speed on spn makes network unusable

### ISSUE THREAD

**Issue by northys** [safing/spn#58]
**What do you want to report?**

~When docker pulls a huge image (docker.elastic.co/logstash/logstash:8.0.1) other connections gets really really slow. I wanted to make a suggestion for portmaster gnome icon that I would love it shows SPN connection status as well while my docker image was building (pulling the base actually) and it took almost a minute before github.com opened. At the same time I opened multiple other sites which is what I do when internet seems not to be working / being slow and none of them opened (`google.com, root.cz, aktualne.cz` but it doesn't matter I think).~

I can rewrite it to simple: when I download big file at full speed on SPN (4-5MB/s) it gets hard to browse the internet. All other requests gets really slow when the one which downloads the file is still active.

When I stop the downloading it takes some time before SPN recovers. I measured it multiple times and it is about 10-15s before web pages start to load instantly again.

**Comment by northys** [comment]
note to myself: just excluding docker from SPN as it just pulls data from nearby CDN edge over https... now i can browse the internet while refreshing docker images on my laptop =)

**Comment by northys** [comment]
> All other requests gets really slow

Timeout is probably a better description.

**Comment by dhaavi** [comment]
Thanks for the report. This is very helpful.

This might be related to the other issue we are seeing that the flow control is behaving weird: Big downloads sometimes "pause" shortly and resume after 5-10 seconds.

Or, it might be that the internal scheduling for some reason decides to only handle on connection. In that case, we'd need to introduce a mechanism that shares the SPN "fairly" between connections.

I will keep this in mind. Next up is fixing the flow control - let's see if that improves things here.
