### ISSUE TITLE
i made some test about a protected streaming service, torrenting and video conferencing.

### ISSUE THREAD

**Issue by ghost** [safing/spn#59]
Hello and thanks you for all of your work on portmaster/spn.

First i have: 1gb as a result from each fast.com and speedtest.net with my raw connection. 
Spn setup in balanced mode

So, i tried to watch some stuff on netlix.
The first time i couldn't play anything (proxy detection).

I seen that the exit node was on a french server hosted by OVH.

I made an app rule for firefox, to exclude the AS16276 (OVH).

So now i am on a dutsh servser hosted by HETZNER, and that works fine, no loading times, all content playable.

For torrenting (not work for me):

All requests appeared on portmaster but i didn't have any internet access or extremly low. As another reported that issues already.

Without spn all works fine.

I shut down the torrenting software it did nothing, i have to reboot portmaster to have an internet access. 

Video conferencing (unusable):

I setup discord in plain vpn mode with a node near to me ( i excluded all the other nodes).

I have +5000 of ping (the maximum of the app), that's just not work i cannot hear or send.

Spn is an amazing project i would like to use every day just start my computer and forget the fact that my connection go to many nodes.

Spn works flawlessy in the other cases, like streaming, browsing.

Thanks you.

**Comment by northys** [comment]
> All requests appeared on portmaster but i didn't have any internet access or extremly low. As another reported that issues already.

I'll just link it #58

**Comment by dhaavi** [comment]
Hey @febreze21, thanks a ton for this elaborate report.

Sorry for the late response, we've been hit by _the wave_.

> So, i tried to watch some stuff on netlix. The first time i couldn't play anything (proxy detection).
> 
> I seen that the exit node was on a french server hosted by OVH.
> 
> I made an app rule for firefox, to exclude the AS16276 (OVH).
> 
> So now i am on a dutsh servser hosted by HETZNER, and that works fine, no loading times, all content playable.

Very nice solution to the problem.
In the future we'd like to have special handling for services that we know are sensitive to "proxies".
In case of OVH it could be that the previous user the IP address also ran a VPN/proxy/Tor and we have inherited that status.
Our network volume is not yet so big that I don't think we would be detected for now.

> For torrenting (not work for me):
> 
> All requests appeared on portmaster but i didn't have any internet access or extremly low. As another reported that issues already.
> 
> Without spn all works fine.
> 
> I shut down the torrenting software it did nothing, i have to reboot portmaster to have an internet access.

Yes, as @northys mentioned, this is likely related to #58.
I already mentioned there that there might be two issues at hand and we will fix the first one in the coming weeks and see if it solves it.

> Video conferencing (unusable):
> 
> I setup discord in plain vpn mode with a node near to me ( i excluded all the other nodes).
> 
> I have +5000 of ping (the maximum of the app), that's just not work i cannot hear or send.

I'm not sure, but I think that discord uses UDP, which I will also be looking into in the coming weeks.
 
> Spn is an amazing project i would like to use every day just start my computer and forget the fact that my connection go to many nodes.

Great to hear you like it! Also, thanks for using it already, albeit the rough edges.
