### ISSUE TITLE
Websites in random language

### ISSUE THREAD

**Issue by northys** [safing/spn#60]
**Which Website or Server are you having troubles with?**

**What did not work?**

When you search something using firefox it gives you autocomplete suggestions from your default search engine. Mine is still google and that means that sometimes I get autocompletion in German and sometimes in English while I'm connected to SPN. Lucky me it never was in Hebrew or Finnish :D

---

@davegson this is probably something we could put in wiki. I'll try to find how to set language permanently for autocomplete. I have found a few sources already but none of them worked.

**Comment by dhaavi** [comment]
> Lucky me it never was in Hebrew or Finnish :D

Haha. That'd be funny. ;)

Yes, we'd had reports of this that websites sometimes would set the language based on the IP.
Leaving it at that right now, will think about it.
