### ISSUE TITLE
Connect to other SPN devices

### ISSUE THREAD

**Issue by cfitz25** [safing/spn#62]
**What would you like to add or change?**:
The ability to connect to devices on the same account or an approved account (id assume using key authentication) within the SPN network directly.
I do realise this may not be possible considering the goals of the network though.

**Why do you and others need this?**:
Would be useful to allow a persons devices to connect to eachother directly through the SPN as it would be faster than it leaving the SPN only to come back in again.

**Comment by dhaavi** [comment]
Hey @cfitz25, this is a great idea and something we have been already thinking about.

Though I must say that it will take some time until we get there and also cannot say how this will actually turn out, but something along those lines will likely end up in the SPN in the future.
