### ISSUE TITLE
Ping doesn't work after I turn off SPN but works for other domains

### ISSUE THREAD

**Issue by northys** [safing/spn#65]
**What happened**:

When I try to ping something while SPN is connected (I know it's not supported) I can't ping even after I turn off SPN but I can ping other domain. It starts to work after a while though... There must be something wrong. Seems like some cache expiry...

**What did you expect to happen?**:

I can ping anything after I turn off SPN.

**How did you reproduce it?**:

1) ping google.com while SPN connected, does nothing
2) turn off SPN
3) ping google.com, does nothing
4) ping google.de, works

google is just example. i experienced it myself on my domains and now i was able to reproduce it using google.com and google.cz. the domain pinged while SPN was connected just can't be pinged after SPN is turned off.

**Debug Information**:
https://support.safing.io/privatebin/?4fea4cb54ddc2435#FLss2JgSTqypfUcZL24mv81eyNazX86dn1mkX4TmJcxG

**Comment by northys** [comment]
Now I can ping google.com so let's say it's about 10 minutes before the domain can be pinged again.

**Comment by northys** [comment]
> I think the proper way to solve this is to actually support pings (ICMP echo/reply) via the SPN - but I don't know yet how we are going to do this...

I would be happy enough (actually more than happy) if I could exclude ICMP traffic from SPN as I mostly care about local stats. I don't wanna see high latency pings around the globe when I run ping or traceroute...

Currently there is no way to do that though because ping is shown under unidentified process app.

**Comment by dhaavi** [comment]
Portmaster now re-evaluates and clears connection verdicts when settings change, so while Ping still does not work with SPN itself, it should immediately work when excluded.

Ping support within SPN is not planned for the near future.
