### ISSUE TITLE
spn/terminal: operation connect failed: [ext] connection error

### ISSUE THREAD

**Issue by northys** [safing/spn#68]
**What happened**:

I opened website which was supposed to redirect to https and for the first time I saw this message. Is this the same error that normally means end of file when the connection goes though HTTPS? I mean this one https://github.com/safing/spn/issues/61

![Screenshot from 2022-04-04 01-29-04](https://user-images.githubusercontent.com/2878126/161454287-d635735a-78a3-4634-bd94-59c008bc5f45.png)

**What did you expect to happen?**:

No errors <3

**How did you reproduce it?**:

:/

**Debug Information**:

**Do you log in UTC when I copy debug infromation? Because the unexpected logs do not match time in screen.**

https://support.safing.io/privatebin/?6f16a0ebb6832ed2#6JuLzhQUnHZjMXJRPgPWcCStMrJv28hcdWovqDhyApHk

**Comment by dhaavi** [comment]
Okay, this is weird. You should normally never see this message.

So, what happened is that the Portmaster saw a connection and redirected it to its SPN entry port. When the connection got there, that part of the Portmaster did not know that this connection was coming, so it 

I checked if there was a race condition, but that does not seem to be the case.
Something that could trigger this is that the connection took over one minute to be redirected to SPN entry port - which could mean that the expected connection was purged already - but this is extremely unlikely, I would say.

I've made a small change to improve this. Please report back when you see it again.

**Comment by dhaavi** [comment]
> Do you log in UTC when I copy debug infromation? Because the unexpected logs do not match time in screen.

Logs should be local time.
