### ISSUE TITLE
Improve Node Rules configuration

### ISSUE THREAD

**Issue by northys** [safing/spn#72]
**What happened**:

I got a little bit confused by Home Node Rules.

It's been a while since I've configured `Home Node Rules` to allow DE. Today I noticed that I'm connected to French OVH node as home server and I had to add `Exclude *` after the `Allow DE`.

**What did you expect to happen?**:

I would expect that by default all nodes / countries are allowed and that everything else is blocked when I add explicit `Allow country` rule. Also I would expect that explicit `Exclude country` allow everything else.

I don't see point in adding both `Exclude country` and `Allow country` rules there so I was surprised that I have to `Exclude/Allow *` as second rule.

**Comment by northys** [comment]
I just behaves the same way as `SPN Rules` for domains. Hmm, it doesn't make sence that each section behaves differently. I'll leave the issue open anyway just to give you my feedback.

Maybe the solution would be to add `Exclude *`/`Include *` automatically when user adds the first rule so the user gets information about what to expect.

**Comment by dhaavi** [comment]
Thanks for the feedback.

How the Node Rules work is not ideal and we already have some nice ideas how to improve on that. Our primary objective was to get them out of the door.
We are thinking about show a list of countries that the SPN currently supports and have users select/deselect countries as they wish.

We specifically don't want a "select a single country" way, as this kills and buries the USP of the SPN - being able to use many nodes at once.

**Comment by northys** [comment]
Allowing home node and excluding * breaks it :D It's interesting that I used it yesterday and reconnected many times without issue.

![Screenshot from 2022-04-15 14-51-06](https://user-images.githubusercontent.com/2878126/163586029-a7dc44e7-2b58-4581-8992-010a097b051a.png)

**Comment by dhaavi** [comment]
Ah, yes. Just had that in testing last week and fixed it. Should be fixed in the next beta release.

**Comment by dhaavi** [comment]
This was fixed back then, but we also now improved the rule quick settings by a lot.

Also, we will further improve home node selection in the near future.
