### ISSUE TITLE
SPN failed to connect.

### ISSUE THREAD

**Issue by svenons** [safing/spn#83]
![image](https://user-images.githubusercontent.com/74974184/172553500-7e96c1d5-015e-499f-9b95-cdd3001bb294.png)

No restrictive firewall.
Country: Latvia
OS: Windows 10
If any information necessary, reply and ask.

**Comment by dhaavi** [comment]
I had a couple more minutes. It seems that the internal state excluded all servers from being eligible as an entry node (= home hub). I don't know why that happened.
Can you try to connect again and copy the debug data from the settings page? I'd like to know more about the internal state of the SPN.

**Comment by dhaavi** [comment]
Thanks!

I've already found one issue that I am now investigating.

But I just realized I forgot one important step in the alternative instructions. Sorry about that.
I really want to know why Portmaster marks the known servers as "Invalid".
I updated the instructions, could you do it again?

**Comment by dhaavi** [comment]
Well, great that it works now!
Too bad though, I'd would have loved to get into this more. It will happen again, so I'll get my chance.

No, thanks, I don't think there would be something in the logs if it works.

Did you perhaps use a different Internet Provider / IP address when reinstalling?
The issue I am investigating is related to location data of the device that might be missing.

**Comment by dhaavi** [comment]
I see. Yes, I don't know either. But will find out eventually.

Exclude from SPN: Just untick "Use SPN".

![image](https://user-images.githubusercontent.com/18184155/172805060-a1521da3-e5e8-440a-a965-15169162c227.png)
