### ISSUE TITLE
Just A Few Things That Don't Work Since Using

### ISSUE THREAD

**Issue by verifiedsyckozis** [safing/spn#86]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/spn/issues?q=is%3Aissue+label%3Abug)
  - [Broken Websites/Services](https://github.com/safing/spn/issues?q=is%3Aissue+label%3A%22website+compatibility%22)
  - [Network Status](https://github.com/safing/spn/issues?q=is%3Aissue+label%3A%22network%22%2C%22network+status%22)

**Which Website or Server are you having troubles with?**

XCloud, PS Plus Premium, GeForce Now, Boosteroid, Plex, Jellyfin

Plex and Jellyfin seem to have been officially broken and require a reinstallation.

The others require me to turn Portmaster off, including spn.

**What did not work?**

Plex and Jellyfin can't find their servers

The game services just don't work, basically.  The program launches and then... nothing.

**Comment by p2anav** [comment]
Thanks for the info. Did you find a workaround for any of those?

**Comment by verifiedsyckozis** [comment]
Not really.  I found the problem though.  It's the DNS issue.  They all have their own it seems.  So since I don't know how to turn them off or even find out which one is their own, I can't really do anything about it.  They do work in Portmaster, but not with spn on.
