### ISSUE TITLE
Login / Register isnt working

### ISSUE THREAD

**Issue by Pdzly** [safing/spn#87]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/spn/issues?q=is%3Aissue+label%3Abug)
  - [Broken Websites/Services](https://github.com/safing/spn/issues?q=is%3Aissue+label%3A%22website+compatibility%22)
  - [Network Status](https://github.com/safing/spn/issues?q=is%3Aissue+label%3A%22network%22%2C%22network+status%22)

**What happened**:
If i try to register i get this error

![grafik](https://user-images.githubusercontent.com/34943569/175770633-77cde8dd-6579-4103-896c-349b2dc86e98.png)

**What did you expect to happen?**:
That i get through the register it

**How did you reproduce it?**:
Just try to register OR login to something

**Debug Information**:

** Not needed is on all platforms....**

**Comment by dhaavi** [comment]
Hey @Pdzly, thanks for the report.

I was not able to reproduce, but will forward to the devs so they can check what the error message says.

**Comment by davegson** [comment]
Hey there, sorry to hear you are experiencing this issue - definitely should be something that should work!

Some thoughts on this note:

- could you re-try after cleaning Safing cookies & cache? Maybe something got corrupted
- did you harden your browser in an extremer than usual sense? We use authenticity headers to secure the website against forgery attacks - if you have a setting which strips these from the web request this might be the cause.

Anyway, do let me know if one of these pointers worked or if the issue remains.

**Comment by Pdzly** [comment]
Ok it was just temporary it functions now :)
